variables:
  azureSubscription: '{ARM ACCESS TOKEN NAME}'
  functionappName: '{NAME OF FUNCTIONAPP}'

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

steps:
- script:
    dotnet restore
    dotnet build --configuration Release
    dotnet test
- task: DotNetCoreCLI@2
  displayName: 'Create function artifact'
  inputs:
    command: publish
    arguments: '--configuration Release --output publish_output'
    projects: '$(System.DefaultWorkingDirectory)/SudokuSolver.Function/SudokuSolver.Function.csproj'
    publishWebProjects: false
    modifyOutputPath: true
    zipAfterPublish: false
- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output/s"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
- task: AzureFunctionApp@1
  displayName: 'Deploy function'
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'functionApp'
    appName: '$(functionappName)'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'runFromPackage'
- task: AzureFileCopy@3
  displayName: 'Deploy Angular App'
  inputs:
    SourcePath: './SudokuSolverApp/dist/*.*'
    azureSubscription: '$(azureSubscription)'
    Destination: 'AzureBlob'
    storage: 'sudokusolverapia6e3'
    ContainerName: '$web'
