# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
- task: AzureFunctionApp@1
  displayName: 'Deploy function'
  inputs:
    azureSubscription: 'Pay-As-You-Go(bd69ef22-5fb9-4fb8-b97b-7a561beb695c)'
    appType: 'functionApp'
    appName: 'sudoku-solver-api'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
- task: AzureFileCopy@3
  displayName: 'Deploy Angular App'
  inputs:
    SourcePath: './SudokuSolverApp/dist'
    azureSubscription: 'Pay-As-You-Go(bd69ef22-5fb9-4fb8-b97b-7a561beb695c)'
    Destination: 'AzureBlob'
    storage: 'sudokusolverapia6e3'
    ContainerName: 'web'
