# Only triggering on master for now. This is functionally a prod build
trigger:
- master

# For Functions SDK, I think
pool:
  vmImage: 'VS2017-Win2016'

jobs:
# Build and deploy our API (Function App)
- job: Build_Function
  steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk 2.1'
      inputs:
        packageType: sdk
        version: 2.1.x
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk 3.0'
      inputs:
        packageType: sdk
        version: 3.x
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: 'restore'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        command: 'build'
        projects: '$(System.DefaultWorkingDirectory)/**/*.csproj'
        arguments: '--configuration Release'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet test'
      inputs:
        command: 'test'
        projects: '$(System.DefaultWorkingDirectory)/**/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'Create function artifact'
      inputs:
        command: publish
        arguments: '--configuration Release --output publish_output'
        projects: '$(System.DefaultWorkingDirectory)/SudokuSolver.Function/SudokuSolver.Function.csproj'
        publishWebProjects: false
        modifyOutputPath: true
        zipAfterPublish: false
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
        includeRootFolder: false
        archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
    - task: AzureFunctionApp@1
      displayName: 'Deploy function'
      inputs:
        azureSubscription: '$(azureSubscription)'
        appType: 'functionApp'
        appName: '$(functionappName)'
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'
        deploymentMethod: 'runFromPackage'

# Build and deploy our Angular app
- job: Build_WebApp
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: '$(System.DefaultWorkingDirectory)/SudokuSolverApp/'
    - task: Npm@1
      inputs:
        command: 'custom'
        workingDir: '$(System.DefaultWorkingDirectory)/SudokuSolverApp/'
        customCommand: 'run-script build'
    - script: |
        dir "./SudokuSolverApp/dist/"
      displayName: 'list cwd contents (verify build)'
    - task: AzureFileCopy@3
      inputs:
        SourcePath: '$(System.DefaultWorkingDirectory)/SudokuSolverApp/dist/*'
        azureSubscription: '$(azureSubscription)'
        Destination: 'AzureBlob'
        storage: 'sudokusolverapia6e3'
        ContainerName: '$web'
        CleanTargetBeforeCopy: true
        CopyFilesInParallel: true